# Generated by Django 4.1.2 on 2022-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalInfoJW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=32, verbose_name="机构IP")),
                ("address", models.CharField(max_length=128, verbose_name="地址")),
                ("name", models.CharField(max_length=64, verbose_name="名称")),
                ("mail", models.CharField(max_length=32, verbose_name="邮编")),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="经度"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="纬度"
                    ),
                ),
            ],
        ),
    ]
