# Generated by Django 4.1.2 on 2022-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_localinfojw"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=32)),
                ("addr", models.CharField(max_length=64)),
            ],
        ),
    ]
