# Generated by Django 4.1.2 on 2022-11-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_detect"),
    ]

    operations = [
        migrations.DeleteModel(name="LocalInfoJW",),
    ]
