# Generated by Django 4.1.2 on 2022-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_delete_localinfojw"),
    ]

    operations = [
        migrations.CreateModel(
            name="TracertResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=32, verbose_name="本机IP")),
                ("dist", models.CharField(max_length=32, verbose_name="目标IP")),
                ("delays", models.CharField(max_length=512, verbose_name="延迟列表")),
            ],
        ),
    ]
