# Generated by Django 4.1.2 on 2022-11-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_tracertresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracertresult",
            name="delays",
            field=models.CharField(max_length=1024, verbose_name="延迟列表"),
        ),
    ]
