# Generated by Django 4.1.2 on 2023-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_mycontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mycontent",
            name="cover",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图1"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover2",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图2"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover3",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图3"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover4",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图4"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover5",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图5"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover6",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图6"
            ),
        ),
        migrations.AlterField(
            model_name="mycontent",
            name="cover7",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="图7"
            ),
        ),
    ]
